version: "3"

services:
  db:
    build:
      context: .
      dockerfile: containers/snippetbox-db/Dockerfile
    image: carletes/snippetbox-db:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - INSERT_SAMPLE_DATA=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
